/** @type {import {  } from "module";('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'surface-variant': '#dee3eb',
        'outline': '#727781',
        'primary-fixed-dim': '#a1c9ff',
        'tertiary-container': '#8d4401',
        'on-surface-variant': '#414750',
        'inverse-on-surface': '#edf1fa',
        'on-secondary-container': '#006e75',
        'on-primary-container': '#afd1ff',
        'background': '#f8f9ff',
        'tertiary-fixed-dim': '#ffb787',
        'surface': '#f8f9ff',
        'surface-container-highest': '#dee3eb',
        'surface-tint': '#1261a3',
        'surface-container-high': '#e4e8f1',
        'secondary-fixed': '#7df4ff',
        'surface-container-low': '#f0f4fd',
        'inverse-primary': '#a1c9ff',
        'primary-container': '#005a9c',
        'secondary-container': '#7af1fc',
        'primary': '#004275',
        'on-error-container': '#93000a',
        'tertiary': '#6a3100',
        'on-primary-fixed-variant': '#00487f',
        'inverse-surface': '#2c3137',
        'on-tertiary-fixed': '#311300',
        'on-tertiary-container': '#ffc29c',
        'surface-container': '#eaeef7',
        'on-background': '#171c22',
        'surface-bright': '#f8f9ff',
        'on-surface': '#171c22',
        'primary-fixed': '#d2e4ff',
        'secondary-fixed-dim': '#5dd8e2',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#004f54',
        'on-secondary-fixed': '#002022',
        'surface-dim': '#d6dae3',
        'on-tertiary-fixed-variant': '#733600',
        'secondary': '#006970',
        'outline-variant': '#c1c7d2',
        'on-primary-fixed': '#001c37',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#ffdcc7',
      },
      fontFamily: {
        headline: ['Public Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};